### ISSUE TITLE
question on 2.1.9 tag

### ISSUE THREAD

**Issue by greenozon** [bluppfisk/coindicator#103]
Hi again!
long time no see ;)

issue on latest 2.1.9 tag (2.1.8 from #97 was OK!)
Host OS: Ubuntu 20.04 LTS x64

```
./install.sh ~/coin
Installing to /home/user/coin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+20.04.20200408.1-0ubuntu1).
python3-gi is already the newest version (3.36.0-1).
patchelf is already the newest version (0.10-2build1).
python3-setuptools-scm is already the newest version (3.4.3-1ubuntu1).
python3-venv is already the newest version (3.8.2-0ubuntu2).
gir1.2-gtk-3.0 is already the newest version (3.24.20-0ubuntu1.1).
python3-pip is already the newest version (20.0.2-5ubuntu1.9).
python3-wheel is already the newest version (0.34.2-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
Processing /root/.cache/pip/wheels/7b/6f/70/7b15a3a5cd6d7075063f6a6d0c5dedb54a3bc7a815de1af51b/coindicator-2.1.9-py3-none-any.whl
Collecting pygame~=2.1.2
  Using cached pygame-2.1.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.7 MB)
Collecting requests~=2.20
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting chardet~=3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna~=2.7
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting PyYAML>=4.2b1
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting urllib3~=1.26.5
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting certifi>=2022.12.7
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Processing /root/.cache/pip/wheels/90/26/09/b3693f5492298447a6e61c52ec5877f1d050709d6895300094/PyGObject-3.42.2-cp38-cp38-linux_x86_64.whl
Collecting notify2~=0.3.1
  Using cached notify2-0.3.1-py2.py3-none-any.whl (8.0 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
Processing /root/.cache/pip/wheels/6f/97/80/5d681c7cfca3321c002cc5f27d7b21116c21f35793d84babaa/pycairo-1.24.0-cp38-cp38-linux_x86_64.whl
Installing collected packages: pygame, certifi, urllib3, charset-normalizer, idna, requests, chardet, PyYAML, pycairo, PyGObject, notify2, coindicator
Successfully installed PyGObject-3.42.2 PyYAML-6.0 certifi-2023.5.7 chardet-3.0.4 charset-normalizer-3.1.0 coindicator-2.1.9 idna-2.10 notify2-0.3.1 pycairo-1.24.0 pygame-2.1.3 requests-2.31.0 urllib3-1.26.16

```

Now trying to run and...

```
coindicator
Traceback (most recent call last):
  File "/home/user/coin/venv/bin/coindicator", line 5, in <module>
    from coin.coin import main
  File "/home/user/coin/venv/lib/python3.8/site-packages/coin/coin.py", line 23, in <module>
    import notify2
  File "/home/user/coin/venv/lib/python3.8/site-packages/notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

```

**Comment by bluppfisk** [comment]
Eek

trying to remove pesky system dependencies is a hassle :) I've sought and found a library that doesn't need dbus-python and can live with a pure python implementation of dbus: desktop-notifier. Let me know how you fare :)

**Comment by greenozon** [comment]
Thanks!
all good on latest release

PS if I select all the plubings (all available exchangers) I do not see some when for example I'd like to see the BTC price for all...
eg: how one could see the Poloniex BTC value? (in usd or usdt)
the GUI shows a limited set (IMHO)

**Comment by bluppfisk** [comment]
hello
the poloniex plugin is using a the legacy poloniex API and not the newest version. I'm a bit short on time atm, but I will accept a good Pull Request on the poloniex plugin that uses the new API. Shouldn't be too difficult if you want to have a go at it
