### ISSUE TITLE
Issues installing? I have Pythin/Git/Pygame installed

### ISSUE THREAD

**Issue by Rexyislive** [bluppfisk/coindicator#81]
When running, I get the following:

`Traceback (most recent call last):
  File "./coin/coin.py", line 18, in <module>
    from indicator import Indicator
  File "/home/stan/Coinindicator/coinprice-indicator/coin/indicator.py", line 8, in <module>
    from alarm import Alarm, AlarmSettingsWindow
  File "/home/stan/Coinindicator/coinprice-indicator/coin/alarm.py", line 4, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
`

**Comment by bluppfisk** [comment]
did you install `python3-pygame` too?

**Comment by bluppfisk** [comment]
I think 2.0.1 solves most of this. If not, please reopen
