### ISSUE TITLE
Problem with installation in Ubuntu 22.04

### ISSUE THREAD

**Issue by peinfant54** [bluppfisk/coindicator#92]
~/coinprice-indicator$ python3 coin/coin.py
pygame 2.1.2 (SDL 2.0.16, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Nombre o servicio desconocido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4d66064a90>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.mxc.com', port=443): Max retries exceeded with url: /open/api/v2/market/symbols (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d66064a90>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/coinprice-indicator/coin/downloader.py", line 47, in execute
    command.response = get(command.url, timeout=command.timeout)
  File "/home/pablo/.local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pablo/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pablo/.local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pablo/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/pablo/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.mxc.com', port=443): Max retries exceeded with url: /open/api/v2/market/symbols (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d66064a90>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/coinprice-indicator/coin/coin.py", line 371, in <module>
    coin = Coin()
  File "/home/pablo/coinprice-indicator/coin/coin.py", line 55, in __init__
    self._load_assets()
  File "/home/pablo/coinprice-indicator/coin/coin.py", line 128, in _load_assets
    exchange.discover_assets(DownloadService(), lambda *args: None)
  File "/home/pablo/coinprice-indicator/coin/exchange.py", line 188, in discover_assets
    downloader.execute(command, cls._handle_discovery_result)
  File "/home/pablo/coinprice-indicator/coin/downloader.py", line 51, in execute
    response_handler(None)
  File "/home/pablo/coinprice-indicator/coin/exchange.py", line 196, in _handle_discovery_result
    logging.debug("Response from {}: {}".format(command.url, command.error))
AttributeError: 'NoneType' object has no attribute 'url'
~/coinprice-indicator$ 

When I did execute "./install.sh" everything went OK.
~/coinprice-indicator$ pip freeze | grep requests
requests==2.27.1
requests-kerberos==0.14.0
requests-ntlm==1.1.0
requests-toolbelt==0.9.1
~/coinprice-indicator$ 

What can I do?

Thanks

**Comment by peinfant54** [comment]
Hi, thanks you for answering me so fast.

Where can I find the user.conf file?

**Comment by nsukucredence** [comment]
Hi @peinfant54 I got it running by going to ~/home/coinprice-indicator/coin/exchanges and delete mxc.py
I hope it works for you. Thanks

**Comment by peinfant54** [comment]
Hi @nsukucredence Thanks, works perfectly!!!

**Comment by bluppfisk** [comment]
That's drastic, but it will work too :)
user.conf is usually in the coinprice-indicator folder

**Comment by RaJiska** [comment]
Hi, little update on this issue; I just had the same after a fresh install. Setting a `mxc: false` in a manually-crafted `user.conf` file did not work. Deleting the whole plugin as suggested above made it work. Perhaps a graceful handling of dead API could be a good to have :)

**Comment by bluppfisk** [comment]
Problem solved in 2.0.1
